"""add financial_statements and financial_ratios

Revision ID: 265745bfe8b8
Revises: 8c42a7bc91d2
Create Date: 2026-08-23 18:46:30.488145

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '265745bfe8b8'
down_revision: str | Sequence[str] | None = '8c42a7bc91d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_ratios',
    sa.Column('financial_ratios_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('business_year', sa.Integer(), nullable=False),
    sa.Column('report_code', sa.String(length=5), nullable=False),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('operating_income', sa.BigInteger(), nullable=True),
    sa.Column('net_income', sa.BigInteger(), nullable=True),
    sa.Column('total_liabilities', sa.BigInteger(), nullable=True),
    sa.Column('total_equity', sa.BigInteger(), nullable=True),
    sa.Column('operating_cash_flow', sa.BigInteger(), nullable=True),
    sa.Column('capex', sa.BigInteger(), nullable=True),
    sa.Column('interest_expense', sa.BigInteger(), nullable=True),
    sa.Column('fcf', sa.BigInteger(), nullable=True),
    sa.Column('depreciation', sa.BigInteger(), nullable=True),
    sa.Column('cash_and_equivalents', sa.BigInteger(), nullable=True),
    sa.Column('total_borrowings', sa.BigInteger(), nullable=True),
    sa.Column('roe', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('debt_ratio', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('interest_coverage', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('dps', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column(
        'created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['corp_code'], ['companies.corp_code'], ),
    sa.PrimaryKeyConstraint('financial_ratios_id'),
    sa.UniqueConstraint('corp_code', 'business_year', 'report_code', name='uq_financial_ratio')
    )
    op.create_table('financial_statements',
    sa.Column('financial_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('business_year', sa.SmallInteger(), nullable=False),
    sa.Column('report_code', sa.String(length=5), nullable=False),
    sa.Column('statement_scope', sa.String(length=10), nullable=False),
    sa.Column('statement_type', sa.String(length=20), nullable=True),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('receipt_no', sa.String(length=20), nullable=True),
    sa.Column(
        'collected_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['corp_code'], ['companies.corp_code'], ),
    sa.PrimaryKeyConstraint('financial_id'),
    sa.UniqueConstraint(
        'corp_code', 'business_year', 'report_code',
        'statement_scope', 'statement_type', 'account_id',
        name='uq_financial_statement'
    )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_statements')
    op.drop_table('financial_ratios')
    # ### end Alembic commands ###
