"""rename ev_ebitda to per, add request_id fk

Revision ID: d8678487fa2f
Revises: 3f828954e17b
Create Date: 2026-08-28 22:48:36.153182

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd8678487fa2f'
down_revision: str | Sequence[str] | None = '3f828954e17b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('portfolio_request_investment_period_check'), 'portfolio_request', type_='check'
    )
    op.drop_constraint(
        op.f('portfolio_request_return_preference_check'), 'portfolio_request', type_='check'
    )
    op.drop_constraint(
        op.f('portfolio_request_risk_preference_check'), 'portfolio_request', type_='check'
    )
    op.drop_constraint(
        op.f('portfolio_request_seed_money_check'), 'portfolio_request', type_='check'
    )
    op.drop_constraint(
        op.f('portfolio_request_valuation_preference_check'), 'portfolio_request', type_='check'
    )
    op.create_check_constraint(
        'ck_portfolio_request_investment_period',
        'portfolio_request',
        "investment_period IN ('UNDER_1_YEAR', 'ONE_TO_THREE_YEARS', 'OVER_3_YEARS')",
    )
    op.create_check_constraint(
        'ck_portfolio_request_return_preference',
        'portfolio_request',
        "return_preference IN ('DIVIDEND', 'CAPITAL_GAIN')",
    )
    op.create_check_constraint(
        'ck_portfolio_request_risk_preference',
        'portfolio_request',
        "risk_preference IN ('STABLE', 'AGGRESSIVE')",
    )
    op.create_check_constraint(
        'ck_portfolio_request_seed_money_positive', 'portfolio_request', 'seed_money > 0'
    )
    op.create_check_constraint(
        'ck_portfolio_request_valuation_preference',
        'portfolio_request',
        "valuation_preference IN ('CURRENT_ASSET', 'FUTURE_EARNINGS')",
    )
    op.add_column(
        'portfolio_result_companies',
        sa.Column('per', sa.Numeric(precision=8, scale=2), nullable=True),
    )
    op.drop_column('portfolio_result_companies', 'ev_ebitda')
    op.add_column(
        'portfolio_results', sa.Column('request_id', sa.BigInteger(), nullable=False)
    )
    op.create_foreign_key(
        'fk_portfolio_results_request',
        'portfolio_results',
        'portfolio_request',
        ['request_id'],
        ['request_id'],
    )
    op.drop_column('portfolio_results', 'valuation_preference')
    op.drop_column('portfolio_results', 'return_preference')
    op.drop_column('portfolio_results', 'investment_period')
    op.drop_column('portfolio_results', 'seed_money')
    op.drop_column('portfolio_results', 'risk_preference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'portfolio_results',
        sa.Column('risk_preference', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    )
    op.add_column(
        'portfolio_results',
        sa.Column('seed_money', sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        'portfolio_results',
        sa.Column(
            'investment_period', sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        'portfolio_results',
        sa.Column(
            'return_preference', sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        'portfolio_results',
        sa.Column(
            'valuation_preference', sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint('fk_portfolio_results_request', 'portfolio_results', type_='foreignkey')
    op.drop_column('portfolio_results', 'request_id')
    op.add_column(
        'portfolio_result_companies',
        sa.Column(
            'ev_ebitda', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True
        ),
    )
    op.drop_column('portfolio_result_companies', 'per')
    op.drop_constraint(
        'ck_portfolio_request_valuation_preference', 'portfolio_request', type_='check'
    )
    op.drop_constraint(
        'ck_portfolio_request_seed_money_positive', 'portfolio_request', type_='check'
    )
    op.drop_constraint(
        'ck_portfolio_request_risk_preference', 'portfolio_request', type_='check'
    )
    op.drop_constraint(
        'ck_portfolio_request_return_preference', 'portfolio_request', type_='check'
    )
    op.drop_constraint(
        'ck_portfolio_request_investment_period', 'portfolio_request', type_='check'
    )
    op.create_check_constraint(
        op.f('portfolio_request_valuation_preference_check'),
        'portfolio_request',
        "valuation_preference::text = ANY (ARRAY["
        "'CURRENT_ASSET'::character varying, 'FUTURE_EARNINGS'::character varying"
        "]::text[])",
    )
    op.create_check_constraint(
        op.f('portfolio_request_seed_money_check'), 'portfolio_request', 'seed_money > 0'
    )
    op.create_check_constraint(
        op.f('portfolio_request_risk_preference_check'),
        'portfolio_request',
        "risk_preference::text = ANY (ARRAY["
        "'STABLE'::character varying, 'AGGRESSIVE'::character varying"
        "]::text[])",
    )
    op.create_check_constraint(
        op.f('portfolio_request_return_preference_check'),
        'portfolio_request',
        "return_preference::text = ANY (ARRAY["
        "'DIVIDEND'::character varying, 'CAPITAL_GAIN'::character varying"
        "]::text[])",
    )
    op.create_check_constraint(
        op.f('portfolio_request_investment_period_check'),
        'portfolio_request',
        "investment_period::text = ANY (ARRAY["
        "'UNDER_1_YEAR'::character varying, 'ONE_TO_THREE_YEARS'::character varying, "
        "'OVER_3_YEARS'::character varying"
        "]::text[])",
    )
    # ### end Alembic commands ###
